services:

  counter:
    build: ./counter

    volumes:
      - ./counter:/src

    ports:
      - 3001:3000

    environment:
      - DB_URL=mongodb+srv://admin:vmHs6gJbMsSmHm5z@testcluster.naqz3.mongodb.net/?retryWrites=true&w=majority&appName=TestCluster

    networks:
      - net

  library:
    build: ./library

    volumes:
      - ./library:/src
      - books:/data/books

    ports: 
      - 3000:3000

    environment:
      - PORT=3000
      - DB_URL=mongodb+srv://admin:vmHs6gJbMsSmHm5z@testcluster.naqz3.mongodb.net/?retryWrites=true&w=majority&appName=TestCluster

    networks:
      - net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: vmHs6gJbMsSmHm5z

volumes:
  books: {}

networks:
  net:
    driver: bridge