services:

  counter:
    build: ./counter

    volumes:
      - ./counter:/src
      - data:/data/views

    ports:
      - 3001:3000

    networks:
      - net

  library:
    build: ./library

    volumes:
      - ./library:/src
      - books:/data/books

    ports: 
      - 3000:3000

    environment:
      - PORT=3000

    networks:
      - net

volumes:
  data: {}
  books: {}

networks:
  net:
    driver: bridge